---
- include_tasks: is_systemd.yml

# Variable configuration.
- include_tasks: variables.yml

- name: Add the shinyproxy group
  group:
    name: "{{ shinyproxy_group }}"
    state: present

- name: Add the shinyproxy user
  user:
    name: "{{ shinyproxy_user }}"
    password_lock: true
    shell: /bin/bash
    group: "{{ shinyproxy_group }}"
    groups: docker
    append: true

- name: Create a network
  docker_network:
    name: "{{ container_network }}"

- name: Make docker daemon listen to port when not internal network
  lineinfile:
    path: /etc/systemd/system/multi-user.target.wants/docker.service
    regex: "ExecStart=.*"
    line: "ExecStart=/usr/bin/dockerd -H fd:// -H tcp://127.0.0.1:2375 --containerd=/run/containerd/containerd.sock"
  when: docker_internal_network is not defined or not docker_internal_network
  notify: restart docker

- name: configure | update (server) configuration file
  template:
    src: application.yml.j2
    dest: /opt/shinyproxy/application.yml
    owner: root
    group: root
    mode: 0644
  notify: restart shinyproxy

- name: Configure the shinyproxy service.
  systemd:
    name: shinyproxy
    state: "{{ shinyproxy_state }}"
    enabled: "{{ shinyproxy_enabled_at_boot }}"
  when: systemd_pid_1 is defined and systemd_pid_1
