---
- name: restart shinyproxy
  systemd: name=shinyproxy state=restarted
  when: systemd_pid_1 is defined and systemd_pid_1

- name: restart docker
  systemd:
    name: docker
    state: restarted
    daemon_reload: yes
  when: systemd_pid_1 is defined and systemd_pid_1
